import { emit, listen, type UnlistenFn } from "@tauri-apps/api/event";
import { getCurrentWindow } from "@tauri-apps/api/window";
import { EventName } from "@core/types/events.js";
import { eventBus, type AppEvents } from "@/entities/events";
import { logger } from "./logger-client";

// ============================================================================
// Event Categories
// ============================================================================

/**
 * Events that should be broadcast across windows (app: prefix).
 * These are cross-window events emitted by one window and received by others.
 */
const BROADCAST_EVENTS = [
  // Agent lifecycle
  EventName.AGENT_SPAWNED,
  EventName.AGENT_STATE,
  EventName.AGENT_COMPLETED,
  EventName.AGENT_ERROR,
  EventName.AGENT_TOOL_COMPLETED,
  EventName.AGENT_CANCELLED,

  // Thread lifecycle
  EventName.THREAD_OPTIMISTIC_CREATED,
  EventName.THREAD_CREATED,
  EventName.THREAD_UPDATED,
  EventName.THREAD_STATUS_CHANGED,
  EventName.THREAD_ARCHIVED,
  EventName.THREAD_FILE_CREATED,
  EventName.THREAD_FILE_MODIFIED,

  // Orchestration
  EventName.WORKTREE_ALLOCATED,
  EventName.WORKTREE_RELEASED,
  EventName.WORKTREE_NAME_GENERATED,

  // User interaction
  EventName.ACTION_REQUESTED,

  // Repository
  EventName.REPOSITORY_CREATED,
  EventName.REPOSITORY_UPDATED,
  EventName.REPOSITORY_DELETED,

  // Settings
  EventName.SETTINGS_UPDATED,

  // Permission flow
  EventName.PERMISSION_REQUEST,
  EventName.PERMISSION_RESPONSE,

  // Queued message acknowledgement
  EventName.QUEUED_MESSAGE_ACK,

  // Plan lifecycle
  EventName.PLAN_DETECTED,
  EventName.PLAN_CREATED,
  EventName.PLAN_UPDATED,
  EventName.PLAN_ARCHIVED,

  // Relation lifecycle
  EventName.RELATION_CREATED,
  EventName.RELATION_UPDATED,

  // User events
  EventName.USER_MESSAGE_SENT,

  // Thread naming
  EventName.THREAD_NAME_GENERATED,
] as const;

/**
 * Events from Rust backend to specific windows.
 * No prefix - Rust emits directly to target window.
 */
const RUST_PANEL_EVENTS = [
  "panel-hidden",
  "panel-shown",
  "spotlight-shown",
  "open-control-panel",
  "clipboard-entry-added",
  "show-error",
] as const;

/**
 * Events coordinating between TypeScript windows.
 * These are emitted by one window and received by another.
 */
const WINDOW_COORDINATION_EVENTS = [] as const;

/**
 * Synthetic events generated by the bridge from Tauri window APIs.
 */
const WINDOW_API_EVENTS = [
  "window:focus-changed",
] as const;

/**
 * Combined local events (all non-broadcast events from Tauri).
 * These are forwarded from Tauri to the local eventBus.
 */
const LOCAL_EVENTS = [
  ...RUST_PANEL_EVENTS,
  ...WINDOW_COORDINATION_EVENTS,
] as const;

type BroadcastEvent = (typeof BROADCAST_EVENTS)[number];
// These types are used for documentation but not directly referenced in code
// type LocalEvent = (typeof LOCAL_EVENTS)[number];
// type WindowApiEvent = (typeof WINDOW_API_EVENTS)[number];

// Runtime check: ensure no overlap between ALL event categories
if (import.meta.env.DEV) {
  const broadcastSet = new Set<string>(BROADCAST_EVENTS as unknown as string[]);
  const localSet = new Set<string>(LOCAL_EVENTS as unknown as string[]);

  // Check LOCAL_EVENTS vs BROADCAST_EVENTS
  for (const event of LOCAL_EVENTS) {
    if (broadcastSet.has(event)) {
      console.error(`[event-bridge] CRITICAL: "${event}" is in both BROADCAST_EVENTS and LOCAL_EVENTS!`);
    }
  }

  // Check WINDOW_API_EVENTS vs BROADCAST_EVENTS
  for (const event of WINDOW_API_EVENTS) {
    if (broadcastSet.has(event)) {
      console.error(`[event-bridge] CRITICAL: "${event}" is in both BROADCAST_EVENTS and WINDOW_API_EVENTS!`);
    }
  }

  // Check WINDOW_API_EVENTS vs LOCAL_EVENTS
  for (const event of WINDOW_API_EVENTS) {
    if (localSet.has(event)) {
      console.error(`[event-bridge] CRITICAL: "${event}" is in both LOCAL_EVENTS and WINDOW_API_EVENTS!`);
    }
  }
}

// ============================================================================
// Module State (for HMR cleanup)
// ============================================================================

let bridgeInitialized = false;
let previousCleanup: UnlistenFn[] = [];

/**
 * Window label used for echo prevention.
 * Cached at module load to avoid repeated calls.
 */
let currentWindowLabel: string | null = null;

function getWindowLabel(): string {
  if (currentWindowLabel === null) {
    currentWindowLabel = getCurrentWindow().label;
  }
  return currentWindowLabel;
}

/**
 * Internal type for broadcast payloads with source tracking.
 * The _source field is added by outgoing bridge and stripped by incoming bridge.
 */
type BroadcastPayload<T = unknown> = T & { _source?: string };

// ============================================================================
// Helpers
// ============================================================================

/**
 * Debug logging toggle for high-volume events.
 * Enable via localStorage.setItem('debug:events', 'true')
 */
function shouldDebugEvents(): boolean {
  return import.meta.env.DEV &&
         typeof localStorage !== 'undefined' &&
         localStorage.getItem('debug:events') === 'true';
}

/**
 * Register a Tauri event listener that forwards to mitt eventBus.
 */
async function registerTauriToMitt(
  tauriEvent: string,
  mittEvent: string
): Promise<UnlistenFn | null> {
  try {
    const unlisten = await listen(tauriEvent, (event) => {
      // Always log spotlight-shown and open-control-panel for debugging
      if (tauriEvent === "spotlight-shown") {
        logger.info(`[event-bridge] 🔦 Received spotlight-shown event, forwarding to mitt`);
      } else if (tauriEvent === "open-control-panel") {
        logger.info(`[event-bridge] 📋 Received open-control-panel event, forwarding to mitt:`, event.payload);
      } else if (shouldDebugEvents()) {
        logger.debug(`[event-bridge] ${tauriEvent} → mitt ${mittEvent}`);
      }
      // Use type assertion since we're bridging between Tauri and mitt types
      eventBus.emit(mittEvent as keyof AppEvents, event.payload as AppEvents[keyof AppEvents]);
    });
    // Log registration for spotlight-shown
    if (tauriEvent === "spotlight-shown") {
      logger.info(`[event-bridge] ✅ Registered listener for spotlight-shown event`);
    }
    return unlisten;
  } catch (error) {
    logger.error(`[event-bridge] Failed to register ${tauriEvent}:`, error);
    return null;
  }
}

/**
 * Register window API event listeners (focus, etc).
 * Returns array for consistency and future extensibility.
 */
async function registerWindowEvents(): Promise<UnlistenFn[]> {
  const unlisteners: UnlistenFn[] = [];

  try {
    const unlisten = await getCurrentWindow().onFocusChanged((event) => {
      if (shouldDebugEvents()) {
        logger.debug(`[event-bridge] window focus changed: ${event.payload}`);
      }
      eventBus.emit("window:focus-changed", { focused: event.payload });
    });
    unlisteners.push(unlisten);
  } catch (error) {
    logger.error(`[event-bridge] Failed to register window focus:`, error);
  }

  return unlisteners;
}

/**
 * Bridges local mitt events to Tauri for cross-window broadcast.
 * Call this in windows that EMIT events (e.g., spotlight).
 *
 * Uses broadcast emit() to ALL windows - receivers filter by threadId.
 * This avoids Tauri bugs with emitTo() and AnyLabel handling (see #11561, #11379).
 *
 * ECHO PREVENTION: Adds `_source` field with window label so receivers can
 * ignore events that originated from the same window.
 */
let outgoingEventCount = 0;

export function setupOutgoingBridge(): void {
  const sourceLabel = getWindowLabel();
  logger.log(`[event-bridge] Setting up OUTGOING bridge (source: ${sourceLabel}) for events:`, BROADCAST_EVENTS);

  for (const eventName of BROADCAST_EVENTS) {
    eventBus.on(eventName, async (payload) => {
      // Skip if this payload already has a _source - it came from another window
      // and we should not re-broadcast it
      const payloadWithSource = payload as BroadcastPayload;
      if (payloadWithSource._source) {
        if (shouldDebugEvents()) {
          logger.debug(`[event-bridge] Skipping re-broadcast of ${eventName} (source: ${payloadWithSource._source})`);
        }
        return;
      }

      outgoingEventCount++;
      const tauriEventName = `app:${eventName}`;

      // Add source label for echo prevention
      const outgoingPayload: BroadcastPayload = { ...payload as object, _source: sourceLabel };

      if (eventName === EventName.AGENT_STATE) {
        const p = payload as Record<string, unknown>;
        logger.log(`[event-bridge] ⚡ OUTGOING agent:state (#${outgoingEventCount}):`, {
          threadId: p?.threadId,
          messageCount: (p?.state as Record<string, unknown>)?.messages instanceof Array
            ? ((p.state as Record<string, unknown[]>).messages).length
            : undefined,
          status: (p?.state as Record<string, unknown>)?.status,
        });
      } else if (eventName === EventName.ACTION_REQUESTED) {
        const p = payload as Record<string, unknown>;
        logger.log(`[event-bridge] 🔔 OUTGOING action-requested (#${outgoingEventCount}):`, {
          threadId: p?.threadId,
          markdownLength: typeof p?.markdown === 'string' ? p.markdown.length : undefined,
          defaultResponse: p?.defaultResponse,
        });
      } else if (eventName === EventName.PLAN_DETECTED) {
        const p = payload as Record<string, unknown>;
        logger.log(`[event-bridge] 📋 OUTGOING plan:detected (#${outgoingEventCount}):`, {
          planId: p?.planId,
          source: sourceLabel,
        });
      } else {
        logger.log(`[event-bridge] OUTGOING: mitt "${eventName}" → Tauri "${tauriEventName}" (broadcast)`, payload);
      }
      // Broadcast to ALL windows - receivers filter by _source and threadId
      await emit(tauriEventName, outgoingPayload);
    });
  }
  logger.log("[event-bridge] Outgoing bridge setup complete");
}

/**
 * Options for selective event subscription.
 * Windows can opt out of event categories they don't need.
 */
export interface IncomingBridgeOptions {
  /**
   * Subscribe to broadcast events from other windows (agent:state, task:updated, etc).
   * Set to false for windows that only emit broadcasts (e.g., spotlight).
   * @default true
   */
  broadcasts?: boolean;

  /**
   * Subscribe to local events from Rust (panel-hidden, open-control-panel, etc).
   * @default true
   */
  local?: boolean;

  /**
   * Subscribe to window API events (window:focus-changed).
   * @default true
   */
  windowApi?: boolean;
}

/**
 * Bridges incoming Tauri events to local mitt.
 * Call this in windows that RECEIVE events (e.g., thread panel).
 *
 * Handles three event categories:
 * - BROADCAST_EVENTS: Cross-window events with app: prefix
 * - LOCAL_EVENTS: Rust panel events and window coordination
 * - WINDOW_API_EVENTS: Synthetic events from window APIs (focus, etc)
 *
 * ECHO PREVENTION: Skips broadcast events where `_source` matches this window's label.
 * This prevents infinite loops when a window has both outgoing and incoming bridges.
 *
 * SELECTIVE SUBSCRIPTION: Use options to subscribe only to needed categories.
 * Windows that emit broadcasts typically don't need to receive them.
 *
 * @example
 * // Spotlight: emits broadcasts, only needs local + windowApi
 * setupIncomingBridge({ broadcasts: false });
 *
 * // Task panel: receive-only, needs all categories
 * setupIncomingBridge(); // defaults to all true
 */
export async function setupIncomingBridge(options: IncomingBridgeOptions = {}): Promise<UnlistenFn[]> {
  const { broadcasts = true, local = true, windowApi = true } = options;
  // HMR support: clean up previous listeners before re-registering
  if (bridgeInitialized && previousCleanup.length > 0) {
    logger.log("[event-bridge] HMR detected - cleaning up previous listeners");
    previousCleanup.forEach(fn => {
      try {
        fn();
      } catch (e) {
        // Log cleanup errors in dev mode to help diagnose issues
        if (import.meta.env.DEV) {
          logger.debug("[event-bridge] HMR cleanup error (non-fatal):", e);
        }
      }
    });
    previousCleanup = [];
  }
  bridgeInitialized = true;

  const currentLabel = getWindowLabel();
  const enabledCategories = [
    broadcasts && 'broadcasts',
    local && 'local',
    windowApi && 'windowApi',
  ].filter(Boolean);
  logger.log(`[event-bridge] Setting up incoming bridge (window: ${currentLabel}, categories: ${enabledCategories.join(', ')})...`);

  // Register broadcast events (app: prefixed from other windows)
  const broadcastResults = broadcasts ? await Promise.all(
    BROADCAST_EVENTS.map(async (eventName) => {
      const tauriEventName = `app:${eventName}`;
      try {
        const unlisten = await listen<BroadcastPayload<AppEvents[BroadcastEvent]>>(
          tauriEventName,
          (event) => {
            const payload = event.payload as BroadcastPayload<Record<string, unknown>>;

            // Log ALL incoming events BEFORE echo check (for debugging)
            if (eventName === EventName.AGENT_STATE || eventName === EventName.AGENT_COMPLETED) {
              logger.log(`[event-bridge] 📥 RAW INCOMING ${eventName} on window "${currentLabel}":`, {
                threadId: payload?.threadId,
                source: payload?._source,
                isEcho: payload._source === currentLabel,
              });
            }

            // ECHO PREVENTION: Skip events that originated from this window
            if (payload._source === currentLabel) {
              if (import.meta.env.DEV && shouldDebugEvents()) {
                logger.debug(`[event-bridge] 🔇 Skipping echo: ${eventName} (source: ${payload._source})`);
              }
              return;
            }

            // IMPORTANT: Keep _source on the payload when emitting to local mitt.
            // The outgoing bridge checks for _source to avoid re-broadcasting events
            // that came from other windows. If we stripped it, the outgoing bridge
            // would think this is a new local event and re-broadcast it, causing an
            // infinite echo loop between windows.
            const sourceLabel = payload._source;

            if (eventName === EventName.AGENT_STATE) {
              logger.log(`[event-bridge] ⚡ INCOMING agent:state:`, {
                threadId: payload?.threadId,
                messageCount: (payload?.state as Record<string, unknown>)?.messages instanceof Array
                  ? (payload.state as Record<string, unknown[]>).messages.length
                  : undefined,
                status: (payload?.state as Record<string, unknown>)?.status,
                source: sourceLabel,
              });
            } else if (eventName === EventName.ACTION_REQUESTED) {
              logger.log(`[event-bridge] 🔔 INCOMING action-requested:`, {
                threadId: payload?.threadId,
                markdownLength: typeof payload?.markdown === 'string' ? payload.markdown.length : undefined,
                defaultResponse: payload?.defaultResponse,
                source: sourceLabel,
              });
            } else if (eventName === EventName.PLAN_DETECTED) {
              logger.log(`[event-bridge] 📋 INCOMING plan:detected:`, {
                planId: payload?.planId,
                source: sourceLabel,
              });
            } else if (shouldDebugEvents()) {
              logger.debug(`[event-bridge] INCOMING: Tauri "${tauriEventName}" → mitt "${eventName}" (source: ${sourceLabel})`);
            }
            // Keep _source so outgoing bridge can detect and skip re-broadcast
            eventBus.emit(eventName, payload as AppEvents[BroadcastEvent]);
          }
        );
        return unlisten;
      } catch (error) {
        logger.error(`[event-bridge] Failed to register listener for: "${tauriEventName}"`, error);
        return null;
      }
    })
  ) : [];

  // Register local events (from Rust backend and window coordination)
  const localResults = local ? await Promise.all(
    LOCAL_EVENTS.map((name) => registerTauriToMitt(name, name))
  ) : [];

  // Register window API events (returns array)
  const windowApiUnlisteners = windowApi ? await registerWindowEvents() : [];

  const unlisteners = [
    ...broadcastResults,
    ...localResults,
    ...windowApiUnlisteners,
  ].filter((fn): fn is UnlistenFn => fn !== null);

  // Store for HMR cleanup
  previousCleanup = unlisteners;

  logger.log(`[event-bridge] ✅ Incoming bridge setup COMPLETE for window "${currentLabel}" - registered ${unlisteners.length} listeners`);

  // Warn if registration count doesn't match expected
  const status = getBridgeStatus();
  if (status.registered < status.expected) {
    logger.warn(`[event-bridge] Only ${status.registered}/${status.expected} listeners registered - some events may not work`);
  }

  return unlisteners;
}

/**
 * Returns the count of successfully registered listeners.
 * Components can use this to verify their required events are available.
 */
export function getBridgeStatus(): { registered: number; expected: number } {
  return {
    registered: previousCleanup.length,
    expected: BROADCAST_EVENTS.length + LOCAL_EVENTS.length + WINDOW_API_EVENTS.length,
  };
}
