/**
 * Thread Diff Generator
 *
 * Generates diffs for files changed during a thread's execution.
 * Uses the initial commit hash captured at thread start to show
 * what changed relative to that point in time.
 *
 * NOTE: Path normalization (absolute to relative) is handled at the agent level.
 * All paths in fileChanges should already be relative when they reach this code.
 * Synthetic diffs for new/untracked files are generated by the Rust backend.
 */

import { gitCommands } from "../tauri-commands";
import { parseDiff, type ParsedDiff } from "../diff-parser";
import { logger } from "../logger-client";

export interface FileChangeInfo {
  path: string;
  operation: "create" | "modify" | "delete" | "rename";
  oldPath?: string;
}

export interface ThreadDiffResult {
  /** Parsed diff data for all changed files */
  diff: ParsedDiff;
  /** The initial commit hash used as base for the diff */
  initialCommit: string;
  /** Error message if diff generation failed */
  error?: string;
}

/**
 * Generate diffs for changed files from the initial commit.
 *
 * @param initialCommitHash - The commit hash captured when the thread started
 * @param fileChanges - Array of file change info with paths and operations
 * @param workingDirectory - The directory where the files are located
 * @returns Parsed diff result with file changes
 */
export async function generateThreadDiff(
  initialCommitHash: string,
  fileChanges: FileChangeInfo[],
  workingDirectory: string
): Promise<ThreadDiffResult> {
  logger.info(`[FC-DEBUG] generateThreadDiff called`, {
    initialCommitHash,
    fileChangesCount: fileChanges.length,
    fileChanges,
    workingDirectory,
  });

  // No files to diff
  if (fileChanges.length === 0) {
    logger.info(`[FC-DEBUG] generateThreadDiff: no files to diff`);
    return {
      diff: { files: [] },
      initialCommit: initialCommitHash,
    };
  }

  try {
    // Build file requests with operation info for the Rust backend
    // Paths should already be relative (normalized at agent level)
    const fileRequests = fileChanges.map((f) => ({
      path: f.path,
      operation: f.operation,
    }));

    logger.info(`[FC-DEBUG] Calling gitCommands.diffFiles with fileRequests`, {
      workingDirectory,
      initialCommitHash,
      fileRequests,
    });

    // Call the Rust backend which handles both tracked files (git diff)
    // and untracked files (synthetic diff generation)
    const rawDiff = await gitCommands.diffFiles(
      workingDirectory,
      initialCommitHash,
      [], // Legacy filePaths param - empty when using fileRequests
      fileRequests
    );

    logger.info(`[FC-DEBUG] gitCommands.diffFiles returned`, {
      rawDiffLength: rawDiff.length,
      rawDiffPreview: rawDiff.substring(0, 500),
    });

    // Parse the diff output
    const parsedDiff = parseDiff(rawDiff);
    logger.info(`[FC-DEBUG] parseDiff returned`, {
      fileCount: parsedDiff.files.length,
      files: parsedDiff.files.map((f) => ({
        oldPath: f.oldPath,
        newPath: f.newPath,
        type: f.type,
        hunkCount: f.hunks.length,
      })),
    });

    return {
      diff: parsedDiff,
      initialCommit: initialCommitHash,
    };
  } catch (err) {
    const errorMessage = err instanceof Error ? err.message : String(err);
    logger.error(`[FC-DEBUG] generateThreadDiff error`, { errorMessage, err });
    return {
      diff: { files: [] },
      initialCommit: initialCommitHash,
      error: `Failed to generate diff: ${errorMessage}`,
    };
  }
}

/**
 * Extract unique file change info from a ThreadState's fileChanges array.
 *
 * @param fileChanges - Array of FileChange objects from ThreadState
 * @returns Array of unique file change info (deduplicated by path)
 */
export function extractFileChanges(
  fileChanges:
    | Array<{
        path: string;
        operation?: "create" | "modify" | "delete" | "rename";
        oldPath?: string;
      }>
    | undefined
): FileChangeInfo[] {
  logger.info(`[FC-DEBUG] extractFileChanges called`, {
    hasFileChanges: !!fileChanges,
    fileChangesCount: fileChanges?.length ?? 0,
    fileChanges: fileChanges?.map((c) => ({ path: c.path, operation: c.operation })) ?? [],
  });

  if (!fileChanges || fileChanges.length === 0) {
    logger.info(`[FC-DEBUG] extractFileChanges: no file changes, returning empty array`);
    return [];
  }

  // Use Map to deduplicate by path, keeping the latest operation
  const changeMap = new Map<string, FileChangeInfo>();
  for (const change of fileChanges) {
    if (change.path) {
      changeMap.set(change.path, {
        path: change.path,
        operation: change.operation ?? "modify", // Default to modify if not specified
        oldPath: change.oldPath,
      });
    }
  }

  const result = Array.from(changeMap.values());
  logger.info(`[FC-DEBUG] extractFileChanges returning`, {
    count: result.length,
    changes: result,
  });
  return result;
}

