import { z } from 'zod';

// ============================================================================
// Context where a quick action is available
// ============================================================================

export const QuickActionContextSchema = z.enum([
  'thread',    // Active thread view
  'plan',      // Active plan view
  'empty',     // No active thread/plan (fresh prompt)
  'all',       // Available in all contexts
]);
export type QuickActionContext = z.infer<typeof QuickActionContextSchema>;

// ============================================================================
// Project Manifest (generated by build script, lives at dist/manifest.json)
// ============================================================================

export const QuickActionManifestEntrySchema = z.object({
  slug: z.string(),            // Human-readable identifier within project, e.g. "archive-and-next"
  title: z.string(),           // Display name
  description: z.string().optional(),
  entryPoint: z.string(),      // Relative path to JS file, e.g. "actions/archive-and-next.js"
  contexts: z.array(QuickActionContextSchema),
});
export type QuickActionManifestEntry = z.infer<typeof QuickActionManifestEntrySchema>;

export const QuickActionManifestSchema = z.object({
  version: z.literal(1),
  sdkVersion: z.string(),      // SDK version used to build, e.g. "1.0.0"
  actions: z.array(QuickActionManifestEntrySchema),
});
export type QuickActionManifest = z.infer<typeof QuickActionManifestSchema>;

// ============================================================================
// Quick Action Metadata (internal representation with UUID)
// ============================================================================

export const QuickActionMetadataSchema = z.object({
  id: z.string().uuid(),                           // Internal UUID (assigned by Mort)
  slug: z.string(),                                // Original slug from manifest
  title: z.string().min(1).max(50),
  description: z.string().max(200).optional(),
  entryPoint: z.string(),                          // Relative path to JS file
  projectPath: z.string(),                         // Absolute path to project directory
  contexts: z.array(QuickActionContextSchema),
  hotkey: z.number().min(0).max(9).optional(),     // 0-9 for Cmd+0 to Cmd+9
  order: z.number().default(0),                    // For manual ordering
  enabled: z.boolean().default(true),
  createdAt: z.number(),
  updatedAt: z.number(),
});
export type QuickActionMetadata = z.infer<typeof QuickActionMetadataSchema>;

// ============================================================================
// Registry (user overrides, stored at ~/.mort/quick-actions-registry.json)
// ============================================================================

export const QuickActionOverrideSchema = z.object({
  hotkey: z.number().min(0).max(9).optional(),
  customOrder: z.number().optional(),
  enabled: z.boolean().optional(),
});
export type QuickActionOverride = z.infer<typeof QuickActionOverrideSchema>;

export const QuickActionsRegistrySchema = z.object({
  // Key is the action's UUID (assigned by Mort on registration)
  actionOverrides: z.record(z.string(), QuickActionOverrideSchema),
  // Map from slug to UUID for stable identification across rebuilds
  slugToId: z.record(z.string(), z.string().uuid()),
});
export type QuickActionsRegistry = z.infer<typeof QuickActionsRegistrySchema>;

// ============================================================================
// Input types for service operations
// ============================================================================

export interface UpdateQuickActionInput {
  hotkey?: number | null;      // null to clear hotkey
  order?: number;
  enabled?: boolean;
}

// ============================================================================
// Resolved Quick Action (for executor)
// ============================================================================

export interface ResolvedQuickAction {
  id: string;
  slug: string;
  title: string;
  description?: string;
  entryPoint: string;          // Relative path, e.g. "actions/archive.js"
  projectPath: string;         // Absolute path to project dir
  contexts: QuickActionContext[];
}
