/**
 * Shared task types used across frontend and agents.
 * This is the single source of truth for task-related types.
 */

import { z } from 'zod';

/**
 * Unified task status used across kanban and workspace views.
 */
export type TaskStatus =
  | "draft"        // Created at spotlight, not yet committed
  | "backlog"      // Ideas, not yet prioritized
  | "todo"         // Prioritized, ready to work on
  | "in-progress"  // Agent actively working
  | "in-review"    // Work done, under review
  | "done"         // Merged and complete
  | "cancelled";   // Abandoned

/** Task statuses in display order (left to right in kanban) */
export const TASK_STATUSES: readonly TaskStatus[] = [
  "draft",
  "backlog",
  "todo",
  "in-progress",
  "in-review",
  "done",
];

/** Statuses that represent active work (agent can be spawned) */
export const ACTIVE_STATUSES: readonly TaskStatus[] = [
  "todo",
  "in-progress",
  "in-review",
];

// ============================================================================
// Zod Schemas - Source of truth for persisted types
// ============================================================================

/**
 * Schema for subtask items within a task.
 */
export const SubtaskSchema = z.object({
  id: z.string(),
  title: z.string(),
  completed: z.boolean(),
});

/**
 * Schema for pending review requests.
 *
 * Reviews are immutable once created - the only mutation allowed is
 * setting `isAddressed` to true via `addressPendingReview`.
 *
 * Note: The `id` field is generated by the persistence layer (not CLI)
 * using `crypto.randomUUID()` when `addPendingReview` is processed.
 */
export const PendingReviewSchema = z.object({
  /** Unique ID for this review request (generated by persistence layer) */
  id: z.string(),
  /** Thread that requested this review */
  threadId: z.string(),
  /** The content to display */
  markdown: z.string(),
  /** Placeholder text, sent on Enter */
  defaultResponse: z.string(),
  /** Timestamp */
  requestedAt: z.number(),
  /** Agent type to spawn on approval (Enter) */
  onApprove: z.string(),
  /** Agent type to spawn on feedback */
  onFeedback: z.string(),
  /** Whether user has responded (false -> true only, never reverts) */
  isAddressed: z.boolean(),
});

/**
 * Schema for task metadata persisted to disk.
 * Validated when loading from JSON files.
 *
 * Supports both regular tasks (with branches, subtasks) and simple tasks
 * (minimal structure). Optional fields with defaults allow simple tasks
 * to use a subset of fields while maintaining type compatibility.
 */
export const TaskMetadataSchema = z.object({
  id: z.string(),
  slug: z.string().optional(),                           // Defaults to id via transform (for simple tasks)
  title: z.string(),
  description: z.string().optional(),
  branchName: z.string().nullable().optional(),          // Nullable for simple tasks (no branch)
  type: z.enum(["work", "investigate", "simple"]),
  subtasks: z.array(SubtaskSchema).default([]),          // Default empty array
  status: z.enum(["draft", "backlog", "todo", "in-progress", "in-review", "done", "cancelled"]),
  createdAt: z.number(),
  updatedAt: z.number(),
  parentId: z.string().nullable().optional(),            // Optional for simple tasks
  // threadIds removed - threads now live in tasks/{slug}/threads/ directory
  tags: z.array(z.string()).default([]),                 // Default empty array
  sortOrder: z.number().optional(),                      // Defaults to createdAt via transform
  /** Repository this task operates on (for workspace management) */
  repositoryName: z.string().optional(),
  /**
   * Array of all review requests for this task.
   *
   * Reviews accumulate over time and are never deleted. To find actionable
   * reviews, filter by `isAddressed === false`.
   *
   * WARNING: This array grows unboundedly. A future cleanup mechanism may
   * be needed for long-running tasks with many review cycles.
   *
   * Defaults to empty array for migration support (older metadata files may not have this field).
   */
  pendingReviews: z.array(PendingReviewSchema).default([]),
  /**
   * Whether the user has approved the work for merge.
   * When true and status is in-review, the merge agent should be spawned.
   */
  reviewApproved: z.boolean().optional(),
  /**
   * Pull request URL when a PR has been created for this task.
   * Set by the merge agent when creating a PR.
   */
  prUrl: z.string().optional(),
  /** Working directory for simple tasks */
  cwd: z.string().optional(),
  /** Path to the worktree this task is using (for explicit worktree management) */
  worktreePath: z.string().optional(),
  /** Plan ID this task is associated with (UUID) */
  planId: z.string().uuid().optional(),
}).transform((data) => ({
  ...data,
  slug: data.slug ?? data.id,                            // Default slug to id for simple tasks
  sortOrder: data.sortOrder ?? data.createdAt,           // Default sortOrder to createdAt
  branchName: data.branchName ?? null,                   // Ensure non-undefined
  parentId: data.parentId ?? null,                       // Ensure non-undefined
}));

// ============================================================================
// Types derived from schemas - NOT separate interface definitions
// ============================================================================

/** Subtask item within a task */
export type Subtask = z.infer<typeof SubtaskSchema>;

/** Pending review request from an agent thread */
export type PendingReview = z.infer<typeof PendingReviewSchema>;

/** Task metadata persisted to disk */
export type TaskMetadata = z.infer<typeof TaskMetadataSchema>;

/** Full task including content */
export interface Task extends TaskMetadata {
  content: string;
}

/** Input for creating a new task */
export interface CreateTaskInput {
  title: string;
  description?: string;
  type?: "work" | "investigate" | "simple";
  status?: TaskStatus;
  parentId?: string | null;
  tags?: string[];
  /** Repository this task operates on (for workspace management) */
  repositoryName?: string;
}

/** Input for updating a task */
export interface UpdateTaskInput {
  title?: string;
  description?: string;
  type?: "work" | "investigate" | "simple";
  slug?: string;
  branchName?: string | null;
  status?: TaskStatus;
  subtasks?: Subtask[];
  tags?: string[];
  sortOrder?: number;
  parentId?: string | null;
  /** Repository this task operates on (for workspace management) */
  repositoryName?: string;
  /**
   * Adds a new pending review to the task.
   * The persistence layer generates the `id` field - callers should not provide it.
   */
  addPendingReview?: Omit<PendingReview, 'id'>;
  /**
   * Marks a review as addressed by its ID.
   *
   * Behavior:
   * - If the ID exists: sets `isAddressed = true` on that review
   * - If the ID does not exist: silently no-ops (no error thrown)
   * - If the review is already addressed: no change
   *
   * This operation is idempotent.
   */
  addressPendingReview?: string;
  /** Whether the review has been approved */
  reviewApproved?: boolean;
  /** Pull request URL when a PR has been created for this task */
  prUrl?: string;
  /** Path to the worktree this task is using (for explicit worktree management) */
  worktreePath?: string;
  /** Plan ID to associate with task, or null to explicitly unset */
  planId?: string | null;
}

/**
 * Generate a unique task ID.
 * Format: task-{timestamp}-{random}
 */
export function generateTaskId(): string {
  const timestamp = Date.now().toString(36);
  const random = Math.random().toString(36).slice(2, 8);
  return `task-${timestamp}-${random}`;
}
