# TODO(anvil-rename): update app name when infra is migrated
app = 'mort-redis'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[mounts]
  source = 'redis_data'
  destination = '/data'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
